[simulation]
identifier = "oneOrAll_N32_0.6"
events = 10000
repetitions = 40
cores = 32
policy = "smash"
default = { "arrival.distribution" = "exponential", "service.distribution" = "exponential" }

[class.1]
cores = 1
arrival.mean = 0.6
service.mean = 1

[class.32]
cores = 32
arrival.lambda = 0.4
service.rate = 1

[class.32F]
cores = 32
arrival.distribution = "frechet"
arrival.alpha = 2.5
#arrival.s = 2
arrival.mean = 2
arrival.m = 0
service.distribution = "bounded pareto"
#service.mean = 1
service.alpha = 1.5
service.rate = 1.5
