identifier = "killsmart_general"
#events = 100000
repetitions = 20
cores = 32

arrival.distribution = "exponential"

service.distribution = "exponential"


[[class]]
cores = 1
arrival.prob = 0.4
service.mean = 1

[[class]]
cores = 4
arrival.prob = 0.3
service.mean = 2

[[class]]
cores = 16
arrival.prob = 0.2
service.mean = 3

[[class]]
cores = 32
arrival.prob = 0.1
service.mean = 5


[[pivot]]
policy = [
    "fifo",
#    "back filling",
#    "most server first",
#    "server filling memoryful",
#    { name ="quick swap", threshold = 1 },
#    { name ="quick swap", threshold = 32 },
#    "first fit",
#    "adaptive msf",
#    "static msf",
#    { name = "smash", window = 2 },
#    { name = "smash", window = 5 },
#    { name = "smash", window = 10 },
     { name = "kill smart", k = 2, v = 1},
     { name = "kill smart", k = 2, v = 2},
     { name = "kill smart", k = 2, v = 3},
     { name = "kill smart", k = 2, v = 4},
     { name = "kill smart", k = 4, v = 1},
     { name = "kill smart", k = 4, v = 2},
     { name = "kill smart", k = 4, v = 3},
     { name = "kill smart", k = 4, v = 4},
]

arrival.rate = [
    0.10,
    0.13,
    0.16,
    0.19,
    0.22,
    0.25,
    0.28,
    0.31,
    0.34,
    0.37,
    0.40,
    0.43,
    0.46,
    0.49,
    0.52,
    0.55,
    0.58,
    0.61,
    0.64,
    0.67,
    0.70,
    0.73,
    0.76,
    0.79,
    0.82,
    0.85,
    0.88,
    0.91,
    0.94,
    0.97,
    1.00,
]