[simulation]
identifier = "oneOrAll-test1-toml"
events = 100000
repetitions = 10
cores = 50
policy = "smash"
smash.window = 1

[simulation.default]
arrival.distribution = "exponential"
service.distribution = "exponential"

[class.1]
cores = 1
arrival.prob = 0.5
arrival.rate = 0.1
service.mean = 0.25

[class.50]
cores = 50
arrival.prob = 0.5
arrival.rate = 0.1
service.mean = 0.5
