[simulation]
identifier = "oneOrAll-test1"
events = 100000
repetitions = 10
cores = 50
policy = "smash"
smash.window = 1

arrival.distribution = "exponential"
arrival.rate = 0.1

service.distribution = "exponential"

[class.1]
cores = 1
arrival.prob = 0.5
service.mean = 0.25

[class.50]
cores = 50
arrival.prob = 0.5
service.mean = 0.5
