identifier = "testing_4C_16"
events = 100000
repetitions = 20
cores = 16
policy = "smash"
smash.window = 1

arrival.distribution = "exponential"
arrival.rate = 0.1

service.distribution = "exponential"
service.mean = 1

[[class]]
cores = 1
arrival.prob = 0.4

[[class]]
cores = 2
arrival.prob = 0.3

[[class]]
cores = 4
arrival.prob = 0.2

[[class]]
cores = 8
arrival.prob = 0.1
