name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - master

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2025
          - windows-11-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-13
          #- macos-14 # arm64
          - macos-15 # arm64
        compiler:
          - gcc-10
          #- gcc-11
          #- gcc-12
          #- gcc-13
          - gcc-14
    steps:
      - uses: actions/checkout@v3
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run configure
        shell: bash
        run: ./configure
