name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - windows-2025
          # - windows-11-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-13
          #- macos-14 # arm64
          - macos-15 # arm64
        compiler:
          - gcc-10
          #- gcc-11
          #- gcc-12
          #- gcc-13
          - gcc-14
        boost:
          - 1.73.0
          - 1.88.0
    steps:
      - uses: actions/checkout@v3
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: ${{ matrix.boost }}
          platform_version: ${{ startsWith(matrix.os, 'ubuntu') && 'linux' || 'macos' }}
          toolset: gcc
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run configure
        shell: bash
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        run: |
          set -e
          ./configure
