name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

_build_steps: &build_steps
  - uses: actions/checkout@v3
  - name: Setup Cpp
    uses: aminya/setup-cpp@v1
    with:
      compiler: ${{ matrix.compiler }}
      cmake: true
  - name: Install boost
    uses: MarkusJx/install-boost@v2
    id: install-boost
    with:
      boost_version: ${{ matrix.boost }}
      platform_version: ${{ matrix.os_version }}
      toolset: ${{ runner.os == 'macOS' && 'clang' || 'gcc' }}
      arch: ${{ runner.os == 'macOS' && runner.arch == 'ARM64' && 'aarch64' || 'x86' }}
  - name: Install uv
    uses: astral-sh/setup-uv@v6
  - name: Run configure
    shell: bash
    env:
      BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    run: |
      set -e
      ./configure

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}-${{matrix.os_version}}${{matrix.os_modifier}}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - windows-2025
          # - windows-11-arm
          - ubuntu
        os_modifier:
          - ""
          - "-arm"
        os_version:
          - "20.04"
          - "22.04"
          - "24.04"
        compiler:
          - gcc-10
          - gcc-11
          #- gcc-12
          #- gcc-13
          - gcc-14
        boost:
          - 1.71.0
          - 1.78.0
          - 1.86.0
          - 1.88.0
        exclude:
          - os_version: 20.04
            boost: 1.88.0
          - os_version: 22.04
            boost: 1.71.0
          - os_version: 22.04
            boost: 1.78.0
          - os_version: 24.04
            boost: 1.71.0
          - os_version: 24.04
            boost: 1.78.0
    steps: *build_steps

  build:
    runs-on: ${{ matrix.os }}-${{matrix.os_version}}${{matrix.os_modifier}}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - windows-2025
          # - windows-11-arm
          - macos
        os_modifier:
          - ""
        os_version:
          - 13
          - 15
        compiler:
          - gcc-11
          #- gcc-12
          #- gcc-13
          - gcc-14
        boost:
          - 1.78.0
          - 1.86.0
          - 1.88.0
    steps: *build_steps
