name: Advanced Usage

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**
  push:
    branches:
      - main
      - feat/docs-and-testing
    paths:
      - docs/**

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: create files list
        id: files_list
        run: |
          mkdir -p output/docs  # create output dir
          # this will also include README.md
          echo "files=$(find . -type f -name "*.md")" > $GITHUB_OUTPUT

      - uses: docker://pandoc/core:3.5
        with:
          args: --output=output/docs/mjqm-docs.pdf ${{ steps.files_list.outputs.files }}

      - uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: output/docs
